# Generated by Django 4.0.3 on 2022-03-30 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetups',
            old_name='discription',
            new_name='description',
        ),
    ]
