# Generated by Django 4.0.3 on 2022-04-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migo', '0002_rename_discription_meetups_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Name',
            new_name='name',
        ),
    ]
